### ISSUE TITLE
How to put on cheat engine?

### ISSUE THREAD

**Issue by Glatrix** [adhptrh/ed3d#2]
Great idea man. Ive been looking for an alternative to ImGui compatible with cheat engine for a while.
One question though, how do put this in cheat engine?

**Comment by adhptrh** [comment]
Sorry for late reply, i rarely check github
On cheat engine menu item select table -> show cheat table lua script and put the script there

**Comment by Glatrix** [comment]
Okay, now If i wanted to paste the example code, where would i put it?
--I'm not gonna copy paste it, just reference it : ) --

**Comment by Glatrix** [comment]
XD
Never mind lol i got it.
For anyone else with this question, put the example below
the GUI code. Then it will work. Nice release!
